### ISSUE TITLE
Support Run Task when Module Name similar Task Name

### ISSUE THREAD

**Issue by thanhtt** [namnv609/tasks-migration#13]
I like this gem, but this gem hasn't allowed running when started of module name is Lower Case
Example:
1. Run
 ```rails generate tasks_migration:task updateInformation```
2. New file generated
```
# app/migration_tasks/update_information_task.rb
class updateInformationTask
  def self.execute
    # Logic here
  end
end
```
3. Add Task into file config
```
# config/tasks_migration.yml
tasks:
  - updateInformation
```
4. Run Task and error
```
bundle exec rake tasks_migration:migrate
Running task updateInformation...
rake aborted!
NameError: wrong constant name updateInformation
/home/framgia/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/home/framgia/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => tasks_migration:migrate
(See full trace by running task with --trace)
```

I think this Gem should support running when Module Name similar Task Name, include snake_case or camelCase ... :D

**Comment by namnv609** [comment]
@thanhtt Ref to #14 :bowing_man:

**Comment by thanhtt** [comment]
ok, goodjob :+1:
